### ISSUE TITLE
hara/string/case.clj not on classpath when using boot

### ISSUE THREAD

**Issue by escherize** [zcaudate/one.love#3]
Hi!

I was trying to load up this library for a talk on RethinkDB + Clojure. However I was unable to require one.love with the following ns form:

`(ns teal.id`
`(:require [one.love :as ol]))`

I think there's an issue with a dependency somewhere (maybe on my machine?)  In any case here's the stack trace:

---
1. Caused by java.io.FileNotFoundException
   Could not locate hara/string/case__init.class or
   hara/string/case.clj on classpath.
2. Unhandled clojure.lang.Compiler$CompilerException
   
   Error compiling one/love/common.clj at (1:1)
                  RT.java:  449  clojure.lang.RT/load
                  RT.java:  412  clojure.lang.RT/load
                 core.clj: 5866  clojure.core/load/fn
                 core.clj: 5865  clojure.core/load
              RestFn.java:  408  clojure.lang.RestFn/invoke
                 core.clj: 5671  clojure.core/load-one
                 core.clj: 5711  clojure.core/load-lib/fn
                 core.clj: 5710  clojure.core/load-lib
              RestFn.java:  142  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5749  clojure.core/load-libs
              RestFn.java:  137  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5832  clojure.core/require
              RestFn.java:  408  clojure.lang.RestFn/invoke
               common.clj:    1  one.love.common/eval55124/loading--auto--
               common.clj:    1  one.love.common/eval55124
            Compiler.java: 6782  clojure.lang.Compiler/eval
            Compiler.java: 6771  clojure.lang.Compiler/eval
            Compiler.java: 7227  clojure.lang.Compiler/load
                  RT.java:  371  clojure.lang.RT/loadResourceScript
                  RT.java:  362  clojure.lang.RT/loadResourceScript
                  RT.java:  446  clojure.lang.RT/load
                  RT.java:  412  clojure.lang.RT/load
                 core.clj: 5866  clojure.core/load/fn
                 core.clj: 5865  clojure.core/load
              RestFn.java:  408  clojure.lang.RestFn/invoke
                 core.clj: 5671  clojure.core/load-one
                 core.clj: 5711  clojure.core/load-lib/fn
                 core.clj: 5710  clojure.core/load-lib
              RestFn.java:  142  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5749  clojure.core/load-libs
              RestFn.java:  137  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5832  clojure.core/require
              RestFn.java:  436  clojure.lang.RestFn/invoke
                 love.clj:    1  one.love/eval55118/loading--auto--
                 love.clj:    1  one.love/eval55118
            Compiler.java: 6782  clojure.lang.Compiler/eval
            Compiler.java: 6771  clojure.lang.Compiler/eval
            Compiler.java: 7227  clojure.lang.Compiler/load
                  RT.java:  371  clojure.lang.RT/loadResourceScript
                  RT.java:  362  clojure.lang.RT/loadResourceScript
                  RT.java:  446  clojure.lang.RT/load
                  RT.java:  412  clojure.lang.RT/load
                 core.clj: 5866  clojure.core/load/fn
                 core.clj: 5865  clojure.core/load
              RestFn.java:  408  clojure.lang.RestFn/invoke
                 core.clj: 5671  clojure.core/load-one
                 core.clj: 5711  clojure.core/load-lib/fn
                 core.clj: 5710  clojure.core/load-lib
              RestFn.java:  142  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5749  clojure.core/load-libs
              RestFn.java:  137  clojure.lang.RestFn/applyTo
                 core.clj:  632  clojure.core/apply
                 core.clj: 5832  clojure.core/require
              RestFn.java:  457  clojure.lang.RestFn/invoke
   boot.user3832318831596198350.clj:    1  teal.id/eval55112/loading--auto--
   boot.user3832318831596198350.clj:    1  teal.id/eval55112
            Compiler.java: 6782  clojure.lang.Compiler/eval
            Compiler.java: 6771  clojure.lang.Compiler/eval
            Compiler.java: 6745  clojure.lang.Compiler/eval
                 core.clj: 3081  clojure.core/eval
                 main.clj:  240  clojure.main/repl/read-eval-print/fn
                 main.clj:  240  clojure.main/repl/read-eval-print
                 main.clj:  258  clojure.main/repl/fn
                 main.clj:  258  clojure.main/repl
              RestFn.java: 1523  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                 AFn.java:  152  clojure.lang.AFn/applyToHelper
                 AFn.java:  144  clojure.lang.AFn/applyTo
                 core.clj:  630  clojure.core/apply
                 core.clj: 1868  clojure.core/with-bindings*
              RestFn.java:  425  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
   interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
   interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                 AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
              Thread.java:  745  java.lang.Thread/run
   `

**Comment by hoebat** [comment]
Hey Brian!

Thanks for picking this up. can you try adding the extra dependency [hara.string.case “2.2.17”] to your project.clj?

I’ll check if it’s a general case.

Chris

**Comment by escherize** [comment]
Hey Chris,

Thanks for the quick response!

I added `[im.chit/hara.string.case "2.2.17"]` , however now I'm getting another error:

basically: `namespace 'one.love.command.ast' not found`.

---

  Show: Clojure Java REPL Tooling Duplicates All  (22 frames hidden)
1. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling one/love/command.clj at (1:1)
   
   ```
             core.clj: 5630  clojure.core/throw-if
          RestFn.java:  442  clojure.lang.RestFn/invoke
             core.clj: 5716  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  482  clojure.lang.RestFn/invoke
          command.clj:    1  one.love.command/eval21706/loading--auto--
          command.clj:    1  one.love.command/eval21706
        Compiler.java: 6782  clojure.lang.Compiler/eval
        Compiler.java: 6771  clojure.lang.Compiler/eval
        Compiler.java: 7227  clojure.lang.Compiler/load
              RT.java:  371  clojure.lang.RT/loadResourceScript
              RT.java:  362  clojure.lang.RT/loadResourceScript
              RT.java:  446  clojure.lang.RT/load
              RT.java:  412  clojure.lang.RT/load
             core.clj: 5866  clojure.core/load/fn
             core.clj: 5865  clojure.core/load
          RestFn.java:  408  clojure.lang.RestFn/invoke
             core.clj: 5671  clojure.core/load-one
             core.clj: 5711  clojure.core/load-lib/fn
             core.clj: 5710  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  436  clojure.lang.RestFn/invoke
             love.clj:    1  one.love/eval21700/loading--auto--
             love.clj:    1  one.love/eval21700
        Compiler.java: 6782  clojure.lang.Compiler/eval
        Compiler.java: 6771  clojure.lang.Compiler/eval
        Compiler.java: 7227  clojure.lang.Compiler/load
              RT.java:  371  clojure.lang.RT/loadResourceScript
              RT.java:  362  clojure.lang.RT/loadResourceScript
              RT.java:  446  clojure.lang.RT/load
              RT.java:  412  clojure.lang.RT/load
             core.clj: 5866  clojure.core/load/fn
             core.clj: 5865  clojure.core/load
          RestFn.java:  408  clojure.lang.RestFn/invoke
             core.clj: 5671  clojure.core/load-one
             core.clj: 5711  clojure.core/load-lib/fn
             core.clj: 5710  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  408  clojure.lang.RestFn/invoke
   ```
   
   boot.user6999153065424403494.clj:    1  one-love/eval21694/loading--auto--
   boot.user6999153065424403494.clj:    1  one-love/eval21694
            Compiler.java: 6782  clojure.lang.Compiler/eval
            Compiler.java: 6771  clojure.lang.Compiler/eval
            Compiler.java: 6745  clojure.lang.Compiler/eval
                 core.clj: 3081  clojure.core/eval
                 main.clj:  240  clojure.main/repl/read-eval-print/fn
                 main.clj:  240  clojure.main/repl/read-eval-print
                 main.clj:  258  clojure.main/repl/fn
                 main.clj:  258  clojure.main/repl
              RestFn.java: 1523  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                 AFn.java:  152  clojure.lang.AFn/applyToHelper
                 AFn.java:  144  clojure.lang.AFn/applyTo
                 core.clj:  630  clojure.core/apply
                 core.clj: 1868  clojure.core/with-bindings*
              RestFn.java:  425  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
   interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
   interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                 AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
              Thread.java:  745  java.lang.Thread/run
2. Caused by java.lang.Exception
   namespace 'one.love.command.ast' not found
   
   ```
             core.clj: 5716  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  482  clojure.lang.RestFn/invoke
          command.clj:    1  one.love.command/eval21706/loading--auto--
          command.clj:    1  one.love.command/eval21706
        Compiler.java: 6782  clojure.lang.Compiler/eval
        Compiler.java: 6771  clojure.lang.Compiler/eval
        Compiler.java: 7227  clojure.lang.Compiler/load
              RT.java:  371  clojure.lang.RT/loadResourceScript
              RT.java:  362  clojure.lang.RT/loadResourceScript
              RT.java:  446  clojure.lang.RT/load
              RT.java:  412  clojure.lang.RT/load
             core.clj: 5866  clojure.core/load/fn
             core.clj: 5865  clojure.core/load
          RestFn.java:  408  clojure.lang.RestFn/invoke
             core.clj: 5671  clojure.core/load-one
             core.clj: 5711  clojure.core/load-lib/fn
             core.clj: 5710  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  436  clojure.lang.RestFn/invoke
             love.clj:    1  one.love/eval21700/loading--auto--
             love.clj:    1  one.love/eval21700
        Compiler.java: 6782  clojure.lang.Compiler/eval
        Compiler.java: 6771  clojure.lang.Compiler/eval
        Compiler.java: 7227  clojure.lang.Compiler/load
              RT.java:  371  clojure.lang.RT/loadResourceScript
              RT.java:  362  clojure.lang.RT/loadResourceScript
              RT.java:  446  clojure.lang.RT/load
              RT.java:  412  clojure.lang.RT/load
             core.clj: 5866  clojure.core/load/fn
             core.clj: 5865  clojure.core/load
          RestFn.java:  408  clojure.lang.RestFn/invoke
             core.clj: 5671  clojure.core/load-one
             core.clj: 5711  clojure.core/load-lib/fn
             core.clj: 5710  clojure.core/load-lib
          RestFn.java:  142  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5749  clojure.core/load-libs
          RestFn.java:  137  clojure.lang.RestFn/applyTo
             core.clj:  632  clojure.core/apply
             core.clj: 5832  clojure.core/require
          RestFn.java:  408  clojure.lang.RestFn/invoke
   ```
   
   boot.user6999153065424403494.clj:    1  one-love/eval21694/loading--auto--
   boot.user6999153065424403494.clj:    1  one-love/eval21694
            Compiler.java: 6782  clojure.lang.Compiler/eval
            Compiler.java: 6771  clojure.lang.Compiler/eval
            Compiler.java: 6745  clojure.lang.Compiler/eval
                 core.clj: 3081  clojure.core/eval
                 main.clj:  240  clojure.main/repl/read-eval-print/fn
                 main.clj:  240  clojure.main/repl/read-eval-print
                 main.clj:  258  clojure.main/repl/fn
                 main.clj:  258  clojure.main/repl
              RestFn.java: 1523  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                 AFn.java:  152  clojure.lang.AFn/applyToHelper
                 AFn.java:  144  clojure.lang.AFn/applyTo
                 core.clj:  630  clojure.core/apply
                 core.clj: 1868  clojure.core/with-bindings*
              RestFn.java:  425  clojure.lang.RestFn/invoke
   interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
   interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
   interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                 AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
              Thread.java:  745  java.lang.Thread/run

**Comment by hoebat** [comment]
Hey Brian,

What’s the link to your project? I’ll take a look.

Chris

**Comment by escherize** [comment]
It's just a sample project -- Here's a link to a project that gives me an error.

https://github.com/escherize/one-love-sample

Maybe I need to blow away .m2?

Edit: removing ~/.m2 was not a fix.

**Comment by hoebat** [comment]
no. it’s my problem…

that’s embarrassing =)

 pushing a fix shortly..

**Comment by hoebat** [comment]
pushed 0.1.1… not sure if it fixes the ‘one.love.command.ast’ thing but please give it a go.

**Comment by escherize** [comment]
Still having the issue T_T

Here's the error - I know it's not very helpful.

https://gist.github.com/c85a8976f1d89be3f33d58bc87a808e2

**Comment by hoebat** [comment]
I think it’s something to do with boot and the way that it loads namespaces. 

the ast namespace dynamically generates the functions used. 

can you try using lein for now?

**Comment by hoebat** [comment]
looking at the error again… It’s caused by a NullPointer somewhere… something to do with the class not being found...

 ZipFile.java:  208  java.util.zip.ZipFile/<init>

Will investigate… but may take some time as i’m not familiar with boot.

**Comment by escherize** [comment]
You are correct! I swapped out boot for lein and it loads without a problem!

This is the first I've heard of that.

**Comment by hoebat** [comment]
awesome =)

well… it’ll be interesting to investigate.

**Comment by myguidingstar-zz** [comment]
the cause is that Boot manipulates the claspath at runtime so the the system property `java.class.path` is not a good source to find the jar.

Anyway, `one.love.command.ast/rethink-ast` is used only once in `one.love.command.ast/classes` whose value is a map of pairs like `{:set-insert com.rethinkdb.gen.ast.SetInsert, :to-geojson com.rethinkdb.gen.ast.ToGeojson ...}`. My proposal is to hardcode the list `[SetInsert ToGeojson ...]` and again derive `one.love.command.ast/classes` using `Class/forName`.

We will keep the script that generates the above list to reuse in case a next java driver version has updates in its ast class list. The script can be a lein command or boot task. Once run, it produces a file `resources/ast-classnames.edn` containing the list. `one.love.command.ast` will load the resource and derive the final `classes`.

Opinion?

**Comment by hoebat** [comment]
wow. yeah i've been too brainwashed by lein to deal with boot. great job on investigating the root cause of the issue

**Comment by hoebat** [comment]
would you mind being a maintainer on the project?

**Comment by myguidingstar-zz** [comment]
I would love to. I've done this (and it works!)
- [x] 1. derive `one.love.command.ast/classes` from `resources/rethinkdb-ast.edn`
- [x] 2. move part of `one.love.command.ast/rethink-ast` to `dev/gen_ast_list.clj` and generate the edn from there

an Boot task only makes sense if one.love switch to Boot. In that case, step 2 will become:
- [ ] 2. migrate project.clj to buid.boot
- [ ] 3. bootify the way to discover .jar

in a project of this size, not much difference :) Now what's your vote?

**Comment by myguidingstar-zz** [comment]
PR for the first approach is ready!

**Comment by hoebat** [comment]
thanks!

**Comment by hoebat** [comment]
@myguidingstar: I accidentally posted a comment on your blog as I thought it was a way to contact you. please delete it. Let me know what you think - my email is z 'at' caudate 'dot' me. Thanks!
